# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseModel')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.basemodel',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BaseModel')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to=b'upload_images')),
                ('thumbnail_100', models.ImageField(blank=True, null=True, upload_to=b'upload_images')),
                ('album_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_gallery.Album')),
            ],
            options={
                'abstract': False,
            },
            bases=('base.basemodel',),
        ),
    ]
